<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.4" />
    <PackageVersion Include="Dapper" Version="2.1.72" />
  </ItemGroup>
</Project>
